version: '3.1'
services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - ny-network
networks: